girar-build: Suggest to fetch gears on  missing gear tag
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/girar-build b/girar-build
--- a/girar-build
+++ b/girar-build
@@ -183,7 +183,7 @@ if [ -n "$indexbase" ] && [ -z "$skip_repo_check" ]; then
 		lastgear=$(echo "$lastbuild" | cut -f5)
 		if [ -n "$lastgear" ]; then
 			lastgear=${lastgear#gear:}
-			lasttag=$(git cat-file -p "$lastgear" | grep -m1 '^tag ')
+			lasttag=$(git cat-file -p "$lastgear" | grep -m1 '^tag ' || fatal "Gear tag not found in this repo, perhaps 'git fetch gears'?")
 			lasttag=${lasttag#tag }
 		fi
 	fi
