girar-build: More version checks
Signed-off-by: Vitaly Chikunov <vt@altlinux.org>

diff --git a/girar-build b/girar-build
--- a/girar-build
+++ b/girar-build
@@ -100,10 +100,24 @@ dir_repo=${url##*:}
 # Check existence of the package.
 if [ -n "$indexbase" ] && [ -z "$skip_repo_check" ]; then
 	indexurl="$indexbase/${name:0:1}/$name/d-t-s-evr.list"
-	if curl -sSfL "$indexurl" | awk "\$4 == \"$tag\"" | grep .; then
-		fatal "The package is already committed to $branch"
+	if ! dts_list=$(curl -sSfL "$indexurl"); then
+		echo "Package $name not found in $branch."
 	else
-		echo "Package not found in $branch."
+		if echo "$dts_list" | awk "\$4 == \"$tag\"" | grep .; then
+			# Just informational and superseded by the following check.
+			echo "The same version $tag is already committed to $branch"
+		fi
+		lastver=$(echo "$dts_list" | tail -1 | cut -f4)
+		cmp=$(rpmevrcmp "$tag" "$lastver")
+		if [ "$cmp" -eq -1 ]; then
+			fatal "There is newer version $lastver > $tag already in $branch"
+		elif [ "$cmp" -eq 0 ]; then
+			fatal "Same version $lastver already latest in $branch"
+		elif [ "$cmp" -eq 1 ]; then
+			echo "This version $tag is newer than last ($lastver) in $branch"
+		else
+			fatal "Version comparison error $tag vs $lastver = $cmp"
+		fi
 	fi
 fi
 
